SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_C_COMPILER "gcc")
SET(CMAKE_CXX_COMPILER "g++")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(SDK_BUILD_PORT "linux")            #芯片型号
SET(SDK_BUILD_OS "linux")              #操作系统，linux/freertos

SET(SDK_CONPONENT_LINK_SUPPORT ON)      #基础连接
SET(SDK_CONPONENT_LOGGER_SUPPORT ON)   

# SET(SDK_CONPONENT_AP_SUPPORT ON)        #AP配网
SET(SDK_CONPONENT_TSL_SUPPORT ON)       #物模型
# SET(SDK_CONPONENT_CONNECT_SUPPORT ON)   #局域网互联互通
SET(SDK_CONPONENT_HUB_SUPPORT ON)       #子设备管理
SET(SDK_CONPONENT_OTA_SUPPORT ON)       #升级
# SET(SDK_CONPONENT_TIME_SUPPORT ON)      #校时

# SET(SDK_ADD_PRIV_INCLUDEDIRS "")

#设置私有编译宏
SET(SDK_ADD_PRIV_PREMACRO "-DRT_USING_SAL -D__FILENAME__='\"$(subst $(dir $<),,$<)\"'")

#设置私有编译参数
# SET(SDK_ADD_PRIV_CFLAGS "")
