SET(CMAKE_SYSTEM_NAME Linux)
SET(TOOCHAIN_C_COMPILER "gcc")
SET(TOOCHAIN_CXX_COMPILER "g++")

#配置测试的领域模块
SET(UNITTEST_KV_ENABLE ON)
SET(UNITTEST_ONLINE_ENABLE ON)
SET(UNITTEST_OTA_ENABLE ON)
SET(UNITTEST_GATEWAY_ENABLE ON)
SET(UNITTEST_TSL_ENABLE ON)
# SET(UNITTEST_LOGGER_ENABLE ON)
SET(UNITTEST_BIND_ENABLE ON)

#配置编译选项,"Debug" || "Release"
SET(CMAKE_BUILD_TYPE "Debug")
SET(CMAKE_BUILD_PORT "linux")
