#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

export IDF_PATH=/opt/esp_sdk/esp-idf
PROJECT_NAME := ut_iotsdk


include $(IDF_PATH)/make/project.mk